/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package printscript.language.app

import kotlinx.cli.* // ktlint-disable no-wildcard-imports
import printscript.language.interpreter.contextProvider.ConsoleContext
import printscript.language.interpreter.interpreter.InterpreterImpl
import printscript.language.interpreter.interpreter.InterpreterWithIterator
import printscript.language.lexer.LexerFactory
import printscript.language.lexer.TokenListIterator
import printscript.language.parser.ASTIterator
import printscript.language.parser.CompleteParser
import java.io.File
import java.io.FileInputStream

enum class MenuOptions {
    Execution,
}

fun execute(fileName: String?, version: String) {
    val fileContent = File(fileName ?: return)
    val lexer = LexerFactory().createLexer(version, FileInputStream(fileContent))
    val tokenListIterator = TokenListIterator(lexer)
    val parser = CompleteParser()
    val astIterator = ASTIterator(parser, tokenListIterator)
    val interpreter = InterpreterWithIterator(InterpreterImpl(ConsoleContext()), astIterator)
    while (interpreter.hasNextInterpretation()) {
        interpreter.interpretNextAST()
    }
}

fun main(args: Array<String>) {
    val parser = ArgParser("printscript")
    val operation by parser.option(
        ArgType.Choice<MenuOptions>(),
        shortName = "o",
        description = "Operation to run",
    ).default(MenuOptions.Execution)
    val input by parser.option(ArgType.String, shortName = "i", description = "Input file")
    val version by parser.option(
        ArgType.Choice(listOf("1.0", "1.1"), { it }),
        shortName = "v",
        description = "Version of program",
    ).default("1.0")
    parser.parse(args)
    when (operation) {
        MenuOptions.Execution -> { execute(input, version)
            // TODO: ADD format and lint operations
        }
    }
}

// "app/src/main/resources/program.txt"
